services:
  othello-server:
    build:
      context: "./docker/ubuntu"
      dockerfile: "Dockerfile"
    ports: 
      - 10000:10000
    volumes:
      - ./src:/app
    command: "bash -c 'gcc /app/server.c -o /app/server && /app/server'"
    stdin_open: true
    tty: true
